from __future__ import annotations

from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def build_fairness_report(payload: dict[str, Any]) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER, title="Unbiased AI Decision Report")
    styles = getSampleStyleSheet()

    elements: list[Any] = []
    elements.append(Paragraph("Unbiased AI Decision Audit Report", styles["Title"]))
    elements.append(Spacer(1, 12))

    dataset = payload.get("dataset_summary", {})
    elements.append(Paragraph("Dataset Summary", styles["Heading2"]))
    dataset_table = Table(
        [
            ["File", dataset.get("file", "-")],
            ["Target", dataset.get("target", "-")],
            ["Sensitive", dataset.get("sensitive", "-")],
            ["Prediction Column", dataset.get("prediction_column", "-")],
            ["Audit Mode", payload.get("audit_mode", "-")],
        ]
    )
    dataset_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ]
        )
    )
    elements.append(dataset_table)
    elements.append(Spacer(1, 12))

    verdict = payload.get("verdict", "unknown")
    elements.append(Paragraph(f"Bias Verdict: <b>{verdict}</b>", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    dp_diff = payload.get("dp_diff", 0)
    eo_diff = payload.get("eo_diff", 0)
    elements.append(Paragraph(f"Demographic Parity Difference: {dp_diff}", styles["BodyText"]))
    elements.append(Paragraph("Meaning: difference in selection rates across groups.", styles["BodyText"]))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph(f"Equalized Odds Difference: {eo_diff}", styles["BodyText"]))
    elements.append(Paragraph("Meaning: gap in error rates across groups.", styles["BodyText"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("Group Metrics", styles["Heading2"]))
    group_metrics = payload.get("group_metrics", {})
    table_data = [["Group", "Accuracy", "Selection Rate"]]
    for group, metrics in group_metrics.items():
        table_data.append([
            str(group),
            str(metrics.get("accuracy", "-")),
            str(metrics.get("selection_rate", "-")),
        ])
    metrics_table = Table(table_data, hAlign="LEFT")
    metrics_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ]
        )
    )
    elements.append(metrics_table)
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("Mitigation Suggestions", styles["Heading2"]))
    suggestions = payload.get("suggestions", [])
    for suggestion in suggestions:
        elements.append(Paragraph(f"- {suggestion}", styles["BodyText"]))
    elements.append(Spacer(1, 16))

    elements.append(Paragraph("Generated by Unbiased AI Decision System", styles["Italic"]))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
